### ISSUE TITLE
Plot of pdf seems to suggest that the truncation is faulty

### ISSUE THREAD

**Issue by pierresegonne** [toshas/torch_truncnorm#1]
Hey! Thanks for sharing this!

To test briefly the truncated normal distribution, I wanted to verify the pdf and wrote the following snippet

```python
import matplotlib.pyplot as plt
import torch

from sggm.vae_model_helper import TruncatedNormal

a = 0
b = 1
mu = 0.8
std = 0.5

p = TruncatedNormal(loc=mu, scale=std, a=a, b=b, validate_args=True)

x = torch.linspace(-0.5, 1.5, 100)

fig, ax = plt.subplots()
ax.plot(x, p.log_prob(x).exp().flatten())

plt.show()
```

Resulting in the following plot profile. Did I completely miss the point or is the truncation not happening ?

Thanks :)
![Figure_1](https://user-images.githubusercontent.com/32778266/106156857-571b9400-6182-11eb-9e29-ab72b08e6faa.png)

**Comment by toshas** [comment]
Thanks for your report! The reason to this behavior is that the check for support doesn't trigger here: https://github.com/toshas/torch_truncnorm/blob/main/TruncatedNormal.py#L90-L93

The actual values within the support should be correct. You can add a check in the given context and either return -inf or throw an exception.

**Comment by pierresegonne** [comment]
Ah right! Thanks for the answer!

Do you want me to propose a fix for this ? :)

**Comment by toshas** [comment]
@pierresegonne thank you, a pull request would be great! I think it'd make sense to copy the behavior of other distributions with a limited support, such as e.g. Beta

**Comment by toshas** [comment]
Committed https://github.com/toshas/torch_truncnorm/commit/7ad2e22e2a26a6cb53234befa06754367b3ad0e0 and detailed in the subsequent commits. Thanks for the initial pull request, I will close it now with this ticket.
